export const DECK = [
  // --- Da Who? (Ituro ang salarin) ---
  { type: "Da Who?", prompt: "Pinaka-marupok sa ex. Shot!", emoji: "🤡" },
  { type: "Da Who?", prompt: "Pinaka-conyo magsalita. Shot!", emoji: "💅" },
  { type: "Da Who?", prompt: "Pinaka-iyakin kapag lasing. Shot!", emoji: "😭" },
  { type: "Da Who?", prompt: "Laging late? Filipino time yarn? Shot!", emoji: "⏰" },
  { type: "Da Who?", prompt: "Pinaka-kuripot sa barkada. Shot!", emoji: "💸" },
  { type: "Da Who?", prompt: "Laging 'On The Way' pero naliligo pa lang. Shot!", emoji: "🚿" },
  { type: "Da Who?", prompt: "Pinaka-mabilis mag-reply sa chat (seen lord). Shot!", emoji: "👀" },
  { type: "Da Who?", prompt: "Pinaka-Tito/Tita pumorma. Shot!", emoji: "polo" },
  { type: "Da Who?", prompt: "Pinaka-maingay tumawa. Shot!", emoji: "🤣" },
  { type: "Da Who?", prompt: "Laging nandadaya sa inuman (Ninja moves). Shot!", emoji: "🥷" },
  { type: "Da Who?", prompt: "Pinaka-malakas mag-aya pero unang natutulog. Shot!", emoji: "💤" },
  { type: "Da Who?", prompt: "Pinaka-strict ang parents. Shot!", emoji: "🚫" },
  { type: "Da Who?", prompt: "Pinaka-drawing sa lakad. Shot!", emoji: "🎨" },
  { type: "Da Who?", prompt: "Laging gutom kahit kakatapos lang kumain. Shot!", emoji: "🍗" },
  { type: "Da Who?", prompt: "Mastermind sa chismis. The Source. Shot!", emoji: "🍵" },
  { type: "Da Who?", prompt: "Pinaka-mahilig mag-English kapag lasing. Shot!", emoji: "🇺🇸" },
  { type: "Da Who?", prompt: "Pinaka-maraming 'ka-talking stage'. Shot, babaero/lalakero!", emoji: "💬" },
  { type: "Da Who?", prompt: "Pinaka-mataas ang pride. Shot para bumaba!", emoji: "🦁" },
  { type: "Da Who?", prompt: "Pinaka-mahilig bumirit sa karaoke. Shot!", emoji: "🎤" },
  { type: "Da Who?", prompt: "Pinaka-mabilis ma-fall. Konting attention lang, in love na. Shot!", emoji: "😍" },
  { type: "Da Who?", prompt: "Pinaka-kaladkarin? Yung laging 'G' agad! Shot!", emoji: "🏃" },
  { type: "Da Who?", prompt: "Pinaka-clout chaser. Shot!", emoji: "🌟" },
  { type: "Da Who?", prompt: "Sino ang laging nauubusan ng pera petsa de peligro pa lang? Shot!", emoji: "📉" },
  { type: "Da Who?", prompt: "Pinaka-mahilig mag-selfie/myday. Shot!", emoji: "📸" },

  // --- Sagot o Lagot ---
  { type: "Sagot o Lagot", prompt: "Ano ang pinaka-nakakahiya mong nagawa sa harap ng crush mo?", emoji: "😳" },
  { type: "Sagot o Lagot", prompt: "Sino sa group na 'to ang jowable? Pangalanan mo o shot!", emoji: "😏" },
  { type: "Sagot o Lagot", prompt: "Kailan ka huling nag-stalk sa ex mo?", emoji: "🕵️" },
  { type: "Sagot o Lagot", prompt: "Ano ang pinakamalaking halaga na inutang mo at di mo binayaran?", emoji: "💰" },
  { type: "Sagot o Lagot", prompt: "Ano ang first impression mo sa katabi mo (kanan)?", emoji: "👉" },
  { type: "Sagot o Lagot", prompt: "Ano ang pinaka-weird na panaginip mo sa group na 'to?", emoji: "👽" },
  { type: "Sagot o Lagot", prompt: "Sinong friend mo ang blinock mo sa FB/IG?", emoji: "🚫" },
  { type: "Sagot o Lagot", prompt: "Kung mayaman ka, sino sa barkada ang hindi mo na kakausapin? And why?", emoji: "🤑" },
  { type: "Sagot o Lagot", prompt: "Sino ang pinaka-hate mong teacher nung High School at bakit?", emoji: "👩‍🏫" },
  { type: "Sagot o Lagot", prompt: "Ano ang pinaka-baliw na bagay na ginawa mo para sa pag-ibig?", emoji: "❤️‍🔥" } ,
  { type: "Sagot o Lagot", prompt: "Kung kailangan mong i-unfriend ang isa dito sa barkada, sino at bakit? (Bawal safe answer!)", emoji: "✂️" },
  { type: "Sagot o Lagot", prompt: "Ano ang password ng phone mo? I-unlock mo o shot!", emoji: "🔓" },
  { type: "Sagot o Lagot", prompt: "Sino dito ang may pinaka-pangit na taste sa jowa?", emoji: "🤮" },
  { type: "Sagot o Lagot", prompt: "Nag-check ka na ba ng phone ng partner mo nang di nila alam?", emoji: "🕵️‍♀️" },
  { type: "Sagot o Lagot", prompt: "Ano ang last thing na sinearch mo sa Google? Show us or Shot!", emoji: "🔍" },
  { type: "Sagot o Lagot", prompt: "Jojowain o Totropahin: Ang katabi mo sa kaliwa?", emoji: "🤔" },
  { type: "Sagot o Lagot", prompt: "Ano ang pinaka-ayaw mong ugali ng katabi mo sa kanan?", emoji: "😒" },
  { type: "Sagot o Lagot", prompt: "Sino sa barkada ang tingin mong unang yayaman?", emoji: "💰" },
  { type: "Sagot o Lagot", prompt: "Kung pwede kang makipag-date sa ex ng kaibigan mo, sino at bakit?", emoji: "🐍" },
  { type: "Sagot o Lagot", prompt: "Kailan ka huling umiyak at bakit?", emoji: "😢" },

  // --- DARE OR SHOT (Gawin o Inumin) ---
  { type: "Dare or Shot", prompt: "I-chat ang crush mo ng 'Miss na kita'. No context.", emoji: "💌" },
  { type: "Dare or Shot", prompt: "Ipakita ang last photo sa gallery mo. No skipping!", emoji: "🖼️" },
  { type: "Dare or Shot", prompt: "Mag-voice message sa ex mo kumanta ng 'All I Want For Christmas Is You'.", emoji: "🎤" },
  { type: "Dare or Shot", prompt: "Sayaw ka ng Budots sa loob ng 10 seconds.", emoji: "🕺" },
  { type: "Dare or Shot", prompt: "Gayahin ang tawa ng katabi mo.", emoji: "🦜" },
  { type: "Dare or Shot", prompt: "Bigyan mo ng 50 pesos ang katabi mo sa kaliwa. (GCash pwede)", emoji: "💸" },
  { type: "Dare or Shot", prompt: "Mag-story ng selfie ngayon na may caption na 'Feeling fresh' kahit haggard. (Good for 24hrs)", emoji: "🤳" },
  { type: "Dare or Shot", prompt: "Huwag mag-Ingles hanggang sa iyong sunod na baraha. Inom pag nagkamali!", emoji: "🇵🇭" },
  { type: "Dare or Shot", prompt: "Ipabasa ang last conversation niyo ng nanay mo.", emoji: "📱" },
  { type: "Dare or Shot", prompt: "Tumawag sa random contact number at sabihing 'Nandito na ang order niyo'.", emoji: "📞" },
  { type: "Dare or Shot", prompt: "Hawakan ang kamay ng katabi mo hanggang next turn.", emoji: "🤝" },
  { type: "Dare or Shot", prompt: "I-DM ang panglimang porfile sa stories mo ng 'Notice me po'.", emoji: "🌟" },
  { type: "Dare or Shot", prompt: "Gayahin si Kris Aquino magsalita for 1 round.", emoji: "💛" },
  { type: "Dare or Shot", prompt: "I-prank call ang isang friend na wala dito. Sabihin mo nakipagbreak ang jowa mo sa 'yo habang umiiyak.", emoji: "😭" },
  { type: "Dare or Shot", prompt: "Sumayaw ng TikTok dance na trending ngayon. Walang music!", emoji: "💃" },
  { type: "Dare or Shot", prompt: "Amuyin ang kili-kili ng katabi (kanan).", emoji: "👃" },
  { type: "Dare or Shot", prompt: "Mag-rap tungkol sa ulam niyo kanina.", emoji: "😎" },
  { type: "Dare or Shot", prompt: "Mag-planking sa sahig for 20 seconds.", emoji: "🪵" },
  { type: "Dare or Shot", prompt: "Inumin ang shot nang walang kamay (gamitin ang bibig lang).", emoji: "🥃" },
  { type: "Dare or Shot", prompt: "Hayaang mag-post ang group ng status sa Facebook mo. Bawal burahin for 1 hour.", emoji: "😈" },
  

  // --- GROUP SHOT / MISC (Lahat damay) ---
  { type: "Group Shot", prompt: "Lahat ng Single! Shot!", emoji: "🍻" },
  { type: "Group Shot", prompt: "Lahat ng Taken... (except sa gusto na humiwalay). Shot!", emoji: "💑" },
  { type: "Group Shot", prompt: "Lahat ng may utang pa sa GCredit/SPayLater. Shot!", emoji: "💳" },
  { type: "Group Shot", prompt: "Lahat ng hindi naligo ngayong araw. Shot!", emoji: "🤢" },
  { type: "Group Shot", prompt: "Lahat ng naka-iPhone. Shot kayo mga rich kid!", emoji: "📱" },
  { type: "Group Shot", prompt: "Lahat ng Android user. Shot!", emoji: "🤖" },
  { type: "Group Shot", prompt: "Lahat ng naka-puti. Shot!", emoji: "⚪" },
  { type: "Group Shot", prompt: "Lahat ng nang-ghost. Shot kayo mga duwag!", emoji: "👻" },
  { type: "Group Shot", prompt: "Lahat ng na-ghost. Shot para sa puso!", emoji: "💔" },
  { type: "Group Shot", prompt: "Cheers! Lahat shot para masaya!", emoji: "🥂" },
  { type: "Group Shot", prompt: "Lahat ng may tattoo o piercing. Shot!", emoji: "💉" },
  { type: "Group Shot", prompt: "Lahat ng palamunin pa rin sa bahay. Shot!", emoji: "🏠" },
  { type: "Group Shot", prompt: "Lahat ng may balak mag-resign pero di magawa. Shot!", emoji: "📝" },
  { type: "Group Shot", prompt: "Lahat ng nagsuka habang umiinom noon. Shot!", emoji: "🤮" },
  { type: "Group Shot", prompt: "Last person na humawak ng cellphone ngayon, shot!", emoji: "📵" },
  { type: "Group Shot", prompt: "Lahat ng naka-salamin (glasses). Shot!", emoji: "🤓" },
  { type: "Group Shot", prompt: "Lahat ng naka-tsinelas lang ngayon. Shot!", emoji: "🩴" },
  { type: "Group Shot", prompt: "Lahat ng panganay sa pamilya. Shot!", emoji: "1️⃣" },
  { type: "Group Shot", prompt: "Lahat ng bunso. Shot!", emoji: "👶" },
  
  // --- SPECIAL EDITION: SAWI / HUGOT (Para sa mga Broken) ---
  { type: "Sawi Edition", prompt: "Lahat ng may picture pa ng ex sa gallery. Shot!", emoji: "📸" },
  { type: "Sawi Edition", prompt: "Lahat ng blinock ng ex. Shot!", emoji: "🚫" },
  { type: "Sawi Edition", prompt: "Nag-chat sa ex nung nakaraang Pasko/New Year? Shot ka marupok!", emoji: "🎄" },
  
  // --- POWER CARDS (Special Game Mechanics) ---
  { type: "Power Card", prompt: "IMMUNITY: Ligtas ka sa susunod na shot.", emoji: "🛡️" },
  { type: "Power Card", prompt: "DRINKING BUDDY: Pumili ng damay. Tig-isa kayong shot.", emoji: "👯" },
  { type: "Power Card", prompt: "REVERSE: Ibalik ang shot sa nagbigay sayo (o sa naunang player).", emoji: "↩️" },
  { type: "Power Card", prompt: "TURO-TURO: Pumikit ka at ituro ang iinom ng shot mo.", emoji: "👉" },
  { type: "Power Card", prompt: "SKIP: Laktawan ang turn mo. (Save mo 'to!)", emoji: "⏭️" },
  { type: "Power Card", prompt: "TRUTH BOMB: Pwede kang magtanong ng kahit ano sa kahit kanino. Pag di sinagot, shot!", emoji: "💣" },


  { type: "Lucky!", prompt: "Ligtas ka! Pumili ng iinom para sayo.", emoji: "🍀" }
];
